app:
    build: ./docker/go
    ports:
      - '5000:5000'
      - '2345:2345'
    volumes:
      - './src:/go/src/github.com/blacknikka/go-auth'
    privileged: true
    tty: true
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    command: realize start --run --no-config
mysql:
    build: ./docker/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret
      TZ: 'Asia/Tokyo'
